import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../style/globals.css';
import Dom from '@/components/dom';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Web2 Next Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Dom>{children}</Dom>
      </body>
    </html>
  );
}
