import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../style/globals.css';
import Providers from '@/contexts/Providers';
import { ReactNode } from 'react';
import Dom from '@/components/dom';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Web2 Next Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  
  return (
    <html lang="en" className='dark'>
      <body
        className={`${inter.className} dark:bg-gray-dark dark:text-[#ffffff]`}
      >
        <Providers>
            <Dom>{children}</Dom>
        </Providers>
      </body>
    </html>
  );
}
